name: book_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_localizations:
    sdk: flutter
  dio: ^5.5.0
  shared_preferences: ^2.2.3
  epub_view: ^3.2.0
  pdfx: ^2.9.2
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^6.0.3
  collection: ^1.18.0
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  share_plus: ^10.0.2
  file_picker: ^8.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  l10n:
    enabled: true
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations

# ✅ launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
